### PR TITLE
[Include Table][Added] Add CSV table to PCB Print

### PR DESCRIPTION
**Pull request by nguyen-v**
This PR adds a new preflight for adding CSV tables to a PCB before print. The preflight takes a list of KiBot outputs and finds the CSV files to plot for them by matching their name with a group name on the PCB (name = `kibot_table_<csv_filename_without_extension>`.

The text alignment (left/center/right), horizontal/vertical spacings, as well as rule widths for headers, top/bottom rule, inter-column/inter-line rules can be configured. Row order can be inverted which is useful when mirroring the PCB texts in print.

The PR still fails the flake8 pre-commit hook, I tried to change the import as suggested but that then fails the ki5/6 workflows.

Examples, where the CSV comes from the output of a BOM with testpoints only:

Centered with only top, header, bottom and mid rules, with extra spaces between rows:
image

Default
image

### CODE REVIEW

**Comment by set-soft** [comment]
Hi @nguyen-v !
Do you have the pre-commit hooks installed on your system? This will run the pre-commit tests before committing, avoiding a lot of changes.

**Comment by set-soft** [comment]
Can you create a couple of simple examples?
I'll apply the PR, but I  want to change some details

**Comment by set-soft** [comment]
I made some important changes, the most relevant:

- The name of the group. Now is something like kibot_table_OUTPUT and optionally kibot_table_OUTPUT[INDEX]. Using the CSV file name is complex, the name of output files can include things like the date or revision, something that changes all the time.
- Removed the `delimiter` option, the information is now extracted from the relevant output

My main concern is the fact that this preflight is a "multi-pass" thing. You must run the BoM/position generation and then run the other outputs with the preflight.

**Comment by nguyen-v** [comment]
> I made some important changes, the most relevant:
> 
> - The name of the group. Now is something like kibot_table_OUTPUT and optionally kibot_table_OUTPUT[INDEX]. Using the CSV file name is complex, the name of output files can include things like the date or revision, something that changes all the time.
> - Removed the `delimiter` option, the information is now extracted from the relevant output
> 
> My main concern is the fact that this preflight is a "multi-pass" thing. You must run the BoM/position generation and then run the other outputs with the preflight.

Thanks for the changes! Yes i was also thinking about the multi-pass issue but I couldn't figure out how to do it otherwise

**Comment by nguyen-v** [comment]
> Can you create a couple of simple examples? I'll apply the PR, but I want to change some details

I guess not, but do you still need examples?

> Do you have the pre-commit hooks installed on your system? This will run the pre-commit tests before committing, avoiding a lot of changes.

I will try to set this up

**Comment by set-soft** [comment]
> I guess not, but do you still need examples?

I added an example/test to the `test_points` test case

**Pull request merged**
