### PR TITLE
[Include Table][Added] Option to force font width

### PR DESCRIPTION
**Pull request by nguyen-v**
This PR adds the `force_font_width` option to the `Include Table` preflight, to specify the desired font width, which overrides the font width that would otherwise be computed by the group width. This is useful when one wants to have different tables with the same vertical spacing.

This PR also fixes the font width and relative column widths computation for the `Include Table` and `Draw Fancy Stackup` preflights. Previously, font width was computed by dividing the table width by the max number of characters of each column. This led to inconsistent results using proportional fonts (as opposed to monospace fonts). The new method correctly computes the font/columns width, taking into account the font and boldness. You can see the difference here 
https://github.com/INTI-CMNB/KiBot/pull/752/files?short_path=cde5c62#diff-cde5c62e0c7ed7774cad41f5bf55cd6e1028b21b7fd90d6bec8b8f00f57f021f

### CODE REVIEW

**Comment by nguyen-v** [comment]
I forgot to recompute the table width when forcing the width, will fix that

**Comment by set-soft** [comment]
Is this changing the default aspect? Why?

**Comment by nguyen-v** [comment]
> Is this changing the default aspect? Why?

The previous method was calculating the font width and column width wrong. Previously, the column width was not taking into account the boldness of the fonts. As for the font width, it was not taking into account the fact that different letters have different widths. This resulted in inconsistent widths for some strings (for example if a string had many 'I', the computed font width would be smaller than it should).

The new method correctly calculates the font width and column width and is now consistent with the description of the spacing parameters (i.e. if you set columb_spacing to 2, there should be exactly 2 em spaces between columns, no matter the boldness/font/content of the cells)

**Comment by set-soft** [comment]
Ok, but now the tables are higher, why?
I'm looking at the diff in the reference image, is not just an adjust in width.

**Comment by nguyen-v** [comment]
> Ok, but now the tables are higher, why? I'm looking at the diff in the reference image, is not just an adjust in width.

Because the font width is changed, it also changes the row spacing (as the row spacing is a multiple of font width)

**Comment by set-soft** [comment]
> . I've also changed the default column_spacing to 1 instead of 2 as I thought that looked better for a default, that also contributes to the computed font width

But then people already using the default will get a quite different result.

**Comment by nguyen-v** [comment]
> But then people already using the default will get a quite different result.

True, to get a closer result to the previous method, I can change the default `column_spacing` to 2 or 3 if you want:
Previous:
image
`column_spacing: 2`
image
`column_spacing: 3`
image

**Comment by set-soft** [comment]
Ok, the idea is to avoid big surprises, small changes are OK, KiCad does it on most releases.

**Comment by nguyen-v** [comment]
Ok, should we settle with `column_spacing: 2` or `column_spacing: 3`? I feel like `column_spacing: 3` looks the closest to the previous result

**Comment by set-soft** [comment]
> Ok, should we settle with `column_spacing: 2` or `column_spacing: 3`? I feel like `column_spacing: 3` looks the closest to the previous result

Yes 3 looks closer

**Pull request merged**
