### PR TITLE
Add github actions readme

### PR DESCRIPTION
**Pull request by sethkaz**
The intention of this is to document some of the basics regarding using KiBot with Github Actions.  I recently implemented KiBot in some repo's actions, and found that the examples didn't really explain how the two systems were linked.  

Also, this is intended to include a minimum viable example so people can be confident implementing it.

Let me know if the readme file is in a good directory, or if there are any extra details you'd like me to add. 

I'll address the TODOs once I have a little more experience implementing this.

### CODE REVIEW

**Comment by set-soft** [comment]
Hi @sethkaz !
The directory is ok. And your contribution is welcome.
I'll merge it when you complete it.
Thanks!

**Comment by sethkaz** [comment]
Hi @set-soft, I was able to target the dev branch, but my "rebase"ing was a bit cumbersome.  I ended up creating a new branch, cherry-picking the commits, and force-with-lease pushing to overwrite it.  Hopefully this didn't create any hidden issues that will cause headaches later.

And sounds good about waiting for me to complete it, though it might be a few weeks before I get my head around all the nuances I'm trying to capture.

**Comment by crgarcia12** [comment]
ping! @set-soft

**Comment by set-soft** [comment]
> ping! @set-soft

I still waiting for @sethkaz completion

**Comment by sethkaz** [comment]
I would say this is mergeable as is.  There is more information I would like to add, but that can be done as a separate PR.

**Pull request merged**
