### PR TITLE
use github actions

### PR DESCRIPTION
**Pull request by nerdyscout**
Hi @set-soft,
I am not really sure if this is a good way to go... this pull request enables KiBot running in the [Github Actions CI](https://github.com/actions/),basically it makes my [kicad-exports](https://github.com/nerdyscout/kicad-exports) obsolete. I know you already have some CI integration, but I think handling this way is much easier. 
Please let me know what you think about it.

### CODE REVIEW

**Comment by set-soft** [comment]
Hi @nerdyscout !
Sorry for the big delay. I was trying to make some KiAuto features with KiCad 5.99 ... and then my son returned home (half the pandemic here and half at his mother's home), and then the car starting to fail ... 

It looks like a very flexible start. I guess more specialized actions can be created as separated github repos. This approach isn't the easiest, but covers all the usage.

I think DRC and ERC deserve separated actions. BTW KiCad 6 will run DRC from Python, fast and realiable!

**Comment by nerdyscout** [comment]
hi,
thank you for merging! unfortunately I just noticed some little bug, as it is just in the Readme I will fix it later hoping there are not more changes needed.

Having specialized actions never came to my mind, might be a good idea. Personally I would use the full approach. 
Currently KiBot does not appear in the Marketplace, I guess after you tag the next release it should pop up there.


hope you and you family stays healthy,
best wishes!

**Comment by set-soft** [comment]
I took a look to this page: https://docs.github.com/en/free-pro-team@latest/actions/creating-actions/publishing-actions-in-github-marketplace

From what I see I just need to use the `Publish this Action to Marketplace`, which is currently available.

But the text recommends using a separated repo. Why? simply because then the action version and README can be customized. They recommend to tag the action according to its API, so you just use `@v1` and you get the input/output params for `v1` of the action, no matters which undelying code is using. 

They also suggest a README layout specific for the actions. From what I see the main README.md is automatically selected and I don't see how to select another README.

Should we use a separated repo? What do you think about it?

**Comment by nerdyscout** [comment]
basically my [kicad-exports](https://github.com/nerdyscout/kicad-exports) is exactly such an separate repository. It is out dated, but does exactly the same. By merging I was hoping to get the same functionality without the need to run updates whenever you improve something with kibot/git-filters/... 
I understand it is much cleaner to keep it separately, the README is really overloaded.
Feel free to remove it, in a independent actions-repository I would suggest to add some generic config.kibot.yaml so ideally the user has not to write this anymore.
eg
- **fabrication** running all gerbers, bom.csv, position.csv so the manufacturer has everything to build the pcb
- **documentation** bom + board and schematic in different file formats
- **renders** images of bottom/front PCB and *.step

or maybe everyone of this could be a independent action

**Comment by set-soft** [comment]
From what I see is more a GitHub limitation that other thing. They like the idea of small repos for every single action, which IMHO is a waste of resources. But I must admit the mechanism is clean and elegant, versions are just tags, names can be directly tied to the repo name, the help and introduction page is just the README, etc.

I don't see any problem in having a generic action in the main repo. But easy to use and clean specialized actions really needs separated repos.

I like the idea of simple actions covering the most common cases. Currently the configuration has some stuff to help, i.e. you can select all copper layers, without needing to know their names or how many are.

Do you want to create these actions? I can add things to help the use of generic configuration files. Each action could have a few options to control things that are indispensable, like the type of gerber files (extended or traditional).

**Comment by nerdyscout** [comment]
I've been thinking about this a while... and some when I forgot to answer :smile: 

small repos, specified for one job are nice, I like the idea also. But at the same time I think it is wasted as the only difference will be the kibot.yaml config.

I made some default configurations, like the one mentioned above, which run fine. Of course you can not handle variants and filters with them. So fare I am running fine by using one action and passing these configs. 

My current [project](https://nerdyscout.github.io/ProMicro/) requires a more advanced [config](https://github.com/nerdyscout/ProMicro/blob/master/config.kiplot.yaml), so i currently not investing into smaller configs.

**Pull request merged**
